import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import { Grid, Card, Text, Button } from '@nextui-org/react';

const inter = Inter({ subsets: ['latin'] })

const MockItem = ({ text }) => {
  return (
    <Card css={{ h: "$24", $$cardColor: '$colors$primary' }}>
      <Card.Body>
        <Button size="xl">
          {/* <Text h6 size={15} color="white" css={{ mt: 0 }}> */}
            {text}
          {/* </Text> */}
        </Button>
      </Card.Body>
    </Card>
  );
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Call Auditor P.O.C.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/logo-png.png"
                alt="ICA"
                className={styles.vercelLogo}
                width={200}
                height={200}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Grid.Container gap={2} justify="center">
            <Grid xs={4}>
              <MockItem text="Login / Register" />
            </Grid>
            <Grid xs={4}>
              <MockItem text="Create / Edit Config" />
            </Grid>
            <Grid xs={4}>
              <MockItem text="My Dashboard" />
            </Grid>
          </Grid.Container>
        </div>

        {/* <div className={styles.grid}>
          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Launch <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Launch the whole thing: file watcher, OpenAI transcriber, scorer and scorecard.
            </p>
          </a>
        </div> */}
      </main>
    </>
  )
}
